### ISSUE TITLE
Surveyform TO-DO

### ISSUE THREAD

**Issue by SachaG** [Devographics/Monorepo#221]
- [ ] We can load less data from the GraphQL API by reusing the shared core templates for certain properties. 
- [x] Get rid of GraphQL for data loading and mutations
- [x] We have two `save-survey` files?
- [x] We have `getSurveyResponseSchema`, `initResponseSchema`, and `getEditionResponseSchema` which all seem to do the same thing?
- [x] We have two `getCommentSchema`?
- [x] Get rid of schema-based validation?

**Comment by eric-burel** [comment]
`save-survey` => one is the gql resolver, the other the actual logic, will disappear when I up date the route handlers

**Comment by eric-burel** [comment]
Closing as most are done and might be outdated
